### ISSUE TITLE
clang assumed in PATH -  CLANGPATH ignored

### ISSUE THREAD

**Issue by shufps** [LedgerHQ/nanox-secure-sdk#1]
First^^ ;-)

When compiling my app, I noticed that the makefile complains there is no clang version 7+ installed.

https://github.com/LedgerHQ/nanox-secure-sdk/blob/master/Makefile.rules_generic#L37

It uses clang from the `$PATH` and ignored `CLANGPATH` that was exported before starting `make`

**Comment by TamtamHero** [comment]
Indeed, good catch, thanks
https://github.com/LedgerHQ/nanox-secure-sdk/blob/master/Makefile.rules_generic

**Comment by pinheadmz** [comment]
Getting this error too - where is `CLANGPATH` supposed to be exported?
