### ISSUE TITLE
Missing cx_Groestl-ref.c file

### ISSUE THREAD

**Issue by gruve-p** [LedgerHQ/nanox-secure-sdk#14]
After trying to compile https://github.com/LedgerHQ/app-groestlcoin/tree/pr-groestl-in-sdk against [Nano X SDK](https://github.com/LedgerHQ/nanox-secure-sdk/) I discovered that it does not compile because of a missing file in this repository.

[This file](https://github.com/LedgerHQ/nanosplus-secure-sdk/blob/main/lib_cxng/src/cx_Groestl-ref.c) is missing [here](https://github.com/LedgerHQ/nanox-secure-sdk/tree/master/lib_cxng/src)

**Comment by xchapron-ledger** [comment]
Should be fixed when using the new SDK https://github.com/LedgerHQ/ledger-secure-sdk/
Else reopen an issue there.
